Завершение вёрстки главной страницы
htmlacademy-adaptive/1501599-pognali-21 pull request #14
Opened 2021-01-24 17:22 UTC by zakrjv

2021-01-25 07:39 UTC, Dima-Dim requested changes

2021-01-25 07:39 UTC, Dima-Dim commented on gulpfile.js
> +  gulp.parallel(
Тут точно `parallel` нужен? Лjкально у меня в папке build только папка css.

2021-01-25 08:07 UTC, zakrjv commented on gulpfile.js
> +  gulp.parallel(
В лекции говорилось, что он нужен. Да и в исходном коде сборки он есть. Я только скрипты не подключала, т.к с js не работала, всё остальное вроде как имеется.
Нашла ошибку, в clean прописала не build, а dist)

2021-01-26 12:00 UTC, Dima-Dim commented
У тебя локально build нормально проходит и собирает папку со всеми нужными файлами?

2021-01-26 16:14 UTC, zakrjv commented on gulpfile.js
> +  gulp.parallel(
> У тебя локально build нормально проходит и собирает папку со всеми нужными файлами?

Да, у меня всё собирается, ничего не теряется.

2021-01-26 16:59 UTC, Dima-Dim commented on gulpfile.js
> +  gulp.parallel(
У меня только папка build\css\ и в ней два файла style.min.css и style.min.css.map. Попробуй у себя удалить папку build и проверить как всё это собирается.

2021-01-26 18:39 UTC, zakrjv commented on gulpfile.js
> +  gulp.parallel(
Так и делала, всё собирается, пользуюсь командами "gulp build" и "npm start"

2021-01-27 08:45 UTC, Dima-Dim commented on gulpfile.js
> +  gulp.parallel(
Пуллриквест приму, но ни у меня локально, ни на гитхабе сборка до конца не проходит. Имей это ввиду.

2021-01-27 08:45 UTC, merged

2021-01-27 08:49 UTC, zakrjv commented on gulpfile.js
> +  gulp.parallel(
А в чем может быть проблема? Как найти ошибку?

2021-01-27 09:50 UTC, Dima-Dim commented on gulpfile.js
> +  gulp.parallel(
Во-первых, старанно что задачи, которые зависят от выполнения предыдущих задач, выполняются параллельно. Например, html, должен подключить спрайт, но на тот момент когда до этого дойдет html задача sprite может быть не выполнена.
Во-вторых, странно что у тебя эта задача build проходит, а у меня и на гитхабе нет. Причём и у меня, и на гитхабе результат одинаковый. Можешь попробовать локально скачать репозиторий в отдельную папку и с нуля установить проект, а потом запустить только задачу build и посмотреть результат. Дальше по ситуации, смотря что получишь, сообщи и будем смотреть дальше.