Стилизация главной страницы
htmlacademy-adaptive/1501599-pognali-21 pull request #5
Opened 2020-12-05 09:53 UTC by zakrjv

2020-12-07 06:28 UTC, Dima-Dim requested changes

2020-12-07 06:28 UTC, Dima-Dim commented on source/less/blocks/about-us.less
> +.about-us__desc--bold {
`about-us__desc--bold` ведь не может быть без `about-us__desc`, значит тут должно быть достаточно только `about-us__desc`.

2020-12-07 06:28 UTC, Dima-Dim commented on source/less/blocks/contacts-list.less
> +.contacts-list__info--color--yellow {
`contacts-list__info--color--yellow` -> `contacts-list__info--color-yellow`

2020-12-07 06:28 UTC, Dima-Dim commented on source/less/blocks/promo.less
> +  line-height: 111%;
https://up.htmlacademy.ru/adaptive/21/criteries#b8
В макете line-height: 40px;

2020-12-07 06:28 UTC, Dima-Dim commented on source/less/fonts.less
> +  src: local("Blogger Sans"), url("../fonts/bloggersans.woff") format("woff"), url("../fonts/bloggersans.woff2") format("woff2");
С начала woff2, иначе браузер видит woff, может его и дальше не смотрит.

2020-12-07 14:25 UTC, zakrjv commented on source/less/blocks/promo.less
> +  line-height: 111%;
В макете указано 40px или 111%. Задала в процентах, чтобы при изменении размера шрифта высота строки пропорционально изменялась :)

2020-12-08 05:11 UTC, Dima-Dim commented on source/less/blocks/promo.less
> +  line-height: 111%;
`/* or 111% */` ?
Я так понимаю, это Figma сама пересчитывает и предлагает как альтернативу.

2020-12-08 05:13 UTC, Dima-Dim approved these changes

2020-12-08 05:13 UTC, merged

2020-12-08 08:30 UTC, zakrjv commented on source/less/blocks/promo.less
> +  line-height: 111%;
То есть всё же лучше указать везде в пикселях?

2020-12-08 12:21 UTC, Dima-Dim commented on source/less/blocks/promo.less
> +  line-height: 111%;
Думаю, в данном случае в пикселях будет более однозначно.